### PR TITLE
Fix build so it does not get stuck

### PR DESCRIPTION
**Pull request by guysoft**
Hey,
So at the moment I am building from CustomPiOS-test2 branch because the master is broken.

Can I merge it so we will be building from master and can also fix it?

### CODE REVIEW

**Comment by jofemodo** [comment]
Ahhh! But "liblrdf-dev" is needed by DISTHRO plugins, so probably this is the problem.
What's the problem with "libraptor2-dev"?

**Comment by guysoft** [comment]
```
Note, selecting 'liblrdf0-dev' instead of 'liblrdf-dev'
The following additional packages will be installed:
  libcurl4-gnutls-dev liblrdf0 libraptor2-0 libraptor2-dev libxml2-dev libxslt1-dev libxslt1.1 libyajl-dev libyajl2
  raptor2-utils
Suggested packages:
  libcurl4-doc libcurl3-dbg libgnutls28-dev libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libraptor2-doc
The following packages will be REMOVED:
  libcurl4-openssl-dev
The following NEW packages will be installed:
  libcurl4-gnutls-dev liblrdf0 liblrdf0-dev libraptor2-0 libraptor2-dev libxml2-dev libxslt1-dev libxslt1.1 libyajl-dev
  libyajl2 raptor2-utils
0 upgraded, 11 newly installed, 1 to remove and 1 not upgraded.
```

Looks like the porblem is that you are trying to install two conflicting packages ``libcurl4-openssl-dev`` and ``liblrdf0-dev``.
```
The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Conflicts: libcurl4-openssl-dev but 7.52.1-5+deb9u5 is to be installed
 libcurl4-openssl-dev : Conflicts: libcurl4-gnutls-dev but 7.52.1-5+deb9u5 is to be installed
```

What needs ``libcurl4-openssl-dev`` and can it work with ``libcurl4-gnutls-dev``?

**Comment by guysoft** [comment]
Trying to build from master

**Comment by guysoft** [comment]
Fixed by removing libcurl4-openssl-dev because it conflicts with libcurl4-gnutls

**Pull request closed without merging**
