### PR TITLE
LV2-Arpeggiator

### PR DESCRIPTION
**Pull request by dcoredump**
New LV2 MIDI tool: Bram Giesen's Arpeggiator (for MOD).

### CODE REVIEW

**Comment by jofemodo** [comment]
Hi @dcoredump !
Is Surge working?

**Comment by jofemodo** [comment]
I didn't have success. Build failed for me ...

**Comment by dcoredump** [comment]
Surge: No, currently some problems. I will take a look at this today (hopefully).

First I will to fix LV2-Arpeggiator.

**Comment by dcoredump** [comment]
I cannot confirm that LV2-Arpegiattor does not work. Can explain what exactly does not do?

**Comment by jofemodo** [comment]
No no, i mean surge. Arppeggiator works fine ;-) Sorry for the missunderstanding ...

**Pull request merged**
