### PR TITLE
Apply patch to tiface.cc

### PR DESCRIPTION
**Pull request by lguyome45**
Add the patch from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931810

### CODE REVIEW

**Comment by jofemodo** [comment]
Jajaja! OK! That's what i call a minimal and very pragmatic patch!! ;-)

**Comment by lguyome45** [comment]
Yes very small patch and I learn a little how sed works.
But, there is a little problem... the file install_aeolus.sh is never called.

**Comment by jofemodo** [comment]
Solved ;-)

**Comment by lguyome45** [comment]
Ok, will try the next image tomorrow. Thank you

**Comment by jofemodo** [comment]
It should be green ... i hope ;-)

**Comment by lguyome45** [comment]
Aeolus open without error and... without sound.
I do a ssh -X do see the gui, and when open, I have not the instrument gui.
I install aeolus by apt, run I have sound.
I remove all file and directory, run install_aeolus and after that it works, I just need to make instrument Off and On on zynthian aeolus gui to have sound.

**Comment by lguyome45** [comment]
I search between a fresh installation and a working.
On the working there is the file /etc/aeolus.conf that is missing on the fresh installation, copy the file and test make aeolus working.

in the install_aeolus.sh just add **echo "-u -J -S /usr/share/aeolus/stops" > /etc/aeolus.conf** and it works, test on a fresh installation with just this line

**Comment by jofemodo** [comment]
Nice! I've tested your fix and it works like a charm!
Now it's in the install file ;-)
Thanks a lot!

**Comment by lguyome45** [comment]
I confirm, works on the latest build 👍

**Pull request merged**
