### PR TITLE
Added overlay and config for Ili9486 3.5 display

### PR DESCRIPTION
**Pull request by buddhafinger**
Added overlay and calibration config for Ili9486 3.5 display.

Touch controller: XPT2046 (ADS7846)
Display controller: ILI 9486

Tested on Raspberry Pi 4 Model B Rev 1.2 with 270 rotation.

### CODE REVIEW

**Comment by jofemodo** [comment]
Hi @buddhafinger !

Ili9486 is not a good name. We already have several configurations for displays with this chip, included the official one, the Zynscreen. You should use the exact brand & model of the display you have tested this configuration.

Same for the webconf's PR.

BTW, did you test this configuration in a fresh burned SD-image? It's important you make a good testing because i can't test as i've not this display in my lab. I must trust you ;-)

Thanks!

**Comment by buddhafinger** [comment]
Hi @jofemodo, 

Thanks for the reply.  

The actual screen which came with a case is listed [here](https://www.amazon.co.uk/gp/product/B09Q3BRGNM/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1)

Would the preferred name be ? 'Owootecc 3.5’’ TFT screen' ?   

Re: Testing,  I'd say my test environment was pretty fresh/clean, but not 100%, so I will do an end to end test on clean image.   My backlog / todo list has grown a bit, so probably won't get around to this until the weekend.  

Thanks!

**Comment by jofemodo** [comment]
You don't need to close the PR, simply fix it ;-)
BTW, "Owootecc-3.5" would be a nice name. Please, although it probably works, try to avoid using "strange characters" on file & dir names.

**Comment by buddhafinger** [comment]
OK, thanks for the steer.  I've updated both forked repos as per this conversation and will resubmit a PR once I've tested on a clean image.

Ta.

**Pull request closed without merging**
