### PR TITLE
Fix for showing model.

### PR DESCRIPTION
**Pull request by dcoredump**
An error is shown when using "cat" to get the model data. I fixed it using "echo" instead of "cat"

### CODE REVIEW

**Comment by jofemodo** [comment]
@dcoredump, i don't understand. If i run both commands i get this:

```
root@zynthian:~# cat /sys/firmware/devicetree/base/model 2>/dev/null
Raspberry Pi 3 Model B Rev 1.2
root@zynthian:~# echo /sys/firmware/devicetree/base/model 2>/dev/null
/sys/firmware/devicetree/base/model
```
As you can see, the "cat" command is working OK for me, and not the "echo" one ... perhaps i'm missing something?

Regards,

**Comment by dcoredump** [comment]
The difference is the calling from a script (like `zynthian-webconf.sh`), like this:

```
# with "echo":
root@zynthian#  source "$ZYNTHIAN_SYS_DIR/scripts/zynthian_envars.sh"
# with "cat":
root@zynthian-stage# source "$ZYNTHIAN_SYS_DIR/scripts/zynthian_envars.sh"
-bash: warning: command substitution: ignored null byte in input
```

**Comment by jofemodo** [comment]
But i don't get any warning when "sourcing" the file:

`source "$ZYNTHIAN_SYS_DIR/scripts/zynthian_envars.sh"`

It's working perfectly for me.  Also, i can's see how the "echo" command can replace the "cat" command...

**Comment by dcoredump** [comment]
This is  strange... I have such errors on several systems. Will try this on my "real" Zynthian at night.

**Comment by dcoredump** [comment]
Ok, try this:
`model=`cat /sys/firmware/devicetree/base/model 2>/dev/null`; echo $model`

This gives for my system:
```
root@zynthian-stage:~# model=`cat /sys/firmware/devicetree/base/model 2>/dev/null`; echo $model
-bash: warning: command substitution: ignored null byte in input
Raspberry Pi 2 Model B Rev 1.1

When I use the command "standalone" it works without error:

```
root@zynthian-stage:~# cat /sys/firmware/devicetree/base/model 2>/dev/null
Raspberry Pi 2 Model B Rev 1.1root@zynthian-stage:~# 
```

So I think replacing the "cat" with the echo is necessary to avoid confusions about error messages.

```

**Comment by jofemodo** [comment]
No warning message in my zynthians:

```
root@zynthian:~# model=`cat /sys/firmware/devicetree/base/model 2>/dev/null`; echo $model
Raspberry Pi 2 Model B Rev 1.1
```

Anyway, i can't see how replacing "cat" with "echo" and work. You can't "echo" the content of a file!!
If you execute:

```
root@zynthian:~# echo /sys/firmware/devicetree/base/model 2>/dev/null
/sys/firmware/devicetree/base/model

```
You echo the "name" of the file, and we need the content! ;-)

Regards,

**Pull request closed without merging**
